1. LOGIT REGRESSION

In [42]:
import matplotlib.pyplot as plt
import pandas as pd
import numpy as np
from sklearn.model_selection import train_test_split

In [49]:
heart_data = pd.read_csv(r'C:\Users\Lan\OneDrive\Máy tính\Python\Python học\Heart.csv')
heart_data

Unnamed: 0  Age  Sex     ChestPain  RestBP  Chol  Fbs  RestECG  MaxHR  \
0             1   63    1       typical     145   233    1        2    150   
1             2   67    1  asymptomatic     160   286    0        2    108   
2             3   67    1  asymptomatic     120   229    0        2    129   
3             4   37    1    nonanginal     130   250    0        0    187   
4             5   41    0    nontypical     130   204    0        2    172   
..          ...  ...  ...           ...     ...   ...  ...      ...    ...   
298         299   45    1       typical     110   264    0        0    132   
299         300   68    1  asymptomatic     144   193    1        0    141   
300         301   57    1  asymptomatic     130   131    0        0    115   
301         302   57    0    nontypical     130   236    0        2    174   
302         303   38    1    nonanginal     138   175    0        0    173   

     ExAng  Oldpeak  Slope   Ca        Thal  AHD  
0        0      2.3      3  0.0       fixed   No  
1        1      1.5      2  3.0      normal  Yes  
2        1      2.6      2  2.0  reversable  Yes  
3        0      3.5      3  0.0      normal   No  
4        0      1.4      1  0.0      normal   No  
..     ...      ...    ...  ...         ...  ...  
298      0      1.2      2  0.0  reversable  Yes  
299      0      3.4      2  2.0  reversable  Yes  
300      1      1.2      2  1.0  reversable  Yes  
301      0      0.0      2  1.0      normal  Yes  
302      0      0.0      1  NaN      normal   No  

[303 rows x 15 columns]

In [50]:
heart_data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 303 entries, 0 to 302
Data columns (total 15 columns):
 #   Column      Non-Null Count  Dtype  
---  ------      --------------  -----  
 0   Unnamed: 0  303 non-null    int64  
 1   Age         303 non-null    int64  
 2   Sex         303 non-null    int64  
 3   ChestPain   303 non-null    object 
 4   RestBP      303 non-null    int64  
 5   Chol        303 non-null    int64  
 6   Fbs         303 non-null    int64  
 7   RestECG     303 non-null    int64  
 8   MaxHR       303 non-null    int64  
 9   ExAng       303 non-null    int64  
 10  Oldpeak     303 non-null    float64
 11  Slope       303 non-null    int64  
 12  Ca          299 non-null    float64
 13  Thal        301 non-null    object 
 14  AHD         303 non-null    object 
dtypes: float64(2), int64(10), object(3)
memory usage: 35.6+ KB


In [51]:
#gán số cho số liệu bảng
from sklearn.preprocessing import LabelEncoder
labelencoder=LabelEncoder()
#chữ đánh thành số , gặp từ số đầu tiên của bảng đến số cuối theo 0,1,2,3,4,...

#for column in df.columns:
#    df[column] = labelencoder.fit_transform(df[column])

labelencoder = LabelEncoder()
heart_data['Thal'] = labelencoder.fit_transform(heart_data['Thal'])
heart_data['ChestPain'] = labelencoder.fit_transform(heart_data['ChestPain'])
heart_data['AHD'] = labelencoder.fit_transform(heart_data['AHD'])
df

Unnamed: 0  Age  Sex  ChestPain  RestBP  Chol  Fbs  RestECG  MaxHR  \
0             0   29    1          3      31    64    1        2     49   
1             1   33    1          0      40   111    0        2     10   
2             2   33    1          0      14    60    0        2     29   
3             3    3    1          1      22    80    0        0     84   
4             4    7    0          2      22    35    0        2     71   
..          ...  ...  ...        ...     ...   ...  ...      ...    ...   
298         298   11    1          3       8    93    0        0     32   
299         299   34    1          0      30    26    1        0     40   
300         300   23    1          0      22     1    0        0     16   
301         301   23    0          2      22    67    0        2     73   
302         302    4    1          1      27    13    0        0     72   

     ExAng  Oldpeak  Slope  Ca  Thal  AHD  
0        0       22      2   0     0    0  
1        1       15      1   3     1    1  
2        1       25      1   2     2    1  
3        0       32      2   0     1    0  
4        0       14      0   0     1    0  
..     ...      ...    ...  ..   ...  ...  
298      0       12      1   0     2    1  
299      0       31      1   2     2    1  
300      1       12      1   1     2    1  
301      0        0      1   1     1    1  
302      0        0      0   4     1    0  

[303 rows x 15 columns]

In [52]:
heart_data.fillna(0, inplace = True)
heart_data

Unnamed: 0  Age  Sex  ChestPain  RestBP  Chol  Fbs  RestECG  MaxHR  \
0             1   63    1          3     145   233    1        2    150   
1             2   67    1          0     160   286    0        2    108   
2             3   67    1          0     120   229    0        2    129   
3             4   37    1          1     130   250    0        0    187   
4             5   41    0          2     130   204    0        2    172   
..          ...  ...  ...        ...     ...   ...  ...      ...    ...   
298         299   45    1          3     110   264    0        0    132   
299         300   68    1          0     144   193    1        0    141   
300         301   57    1          0     130   131    0        0    115   
301         302   57    0          2     130   236    0        2    174   
302         303   38    1          1     138   175    0        0    173   

     ExAng  Oldpeak  Slope   Ca  Thal  AHD  
0        0      2.3      3  0.0     0    0  
1        1      1.5      2  3.0     1    1  
2        1      2.6      2  2.0     2    1  
3        0      3.5      3  0.0     1    0  
4        0      1.4      1  0.0     1    0  
..     ...      ...    ...  ...   ...  ...  
298      0      1.2      2  0.0     2    1  
299      0      3.4      2  2.0     2    1  
300      1      1.2      2  1.0     2    1  
301      0      0.0      2  1.0     1    1  
302      0      0.0      1  0.0     1    0  

[303 rows x 15 columns]

In [54]:
heart_data.isna().sum()

Unnamed: 0    0
Age           0
Sex           0
ChestPain     0
RestBP        0
Chol          0
Fbs           0
RestECG       0
MaxHR         0
ExAng         0
Oldpeak       0
Slope         0
Ca            0
Thal          0
AHD           0
dtype: int64

In [55]:
heart_data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 303 entries, 0 to 302
Data columns (total 15 columns):
 #   Column      Non-Null Count  Dtype  
---  ------      --------------  -----  
 0   Unnamed: 0  303 non-null    int64  
 1   Age         303 non-null    int64  
 2   Sex         303 non-null    int64  
 3   ChestPain   303 non-null    int32  
 4   RestBP      303 non-null    int64  
 5   Chol        303 non-null    int64  
 6   Fbs         303 non-null    int64  
 7   RestECG     303 non-null    int64  
 8   MaxHR       303 non-null    int64  
 9   ExAng       303 non-null    int64  
 10  Oldpeak     303 non-null    float64
 11  Slope       303 non-null    int64  
 12  Ca          303 non-null    float64
 13  Thal        303 non-null    int32  
 14  AHD         303 non-null    int32  
dtypes: float64(2), int32(3), int64(10)
memory usage: 32.1 KB


In [56]:
heart_data['Thal'].value_counts()

1    166
2    117
0     18
3      2
Name: Thal, dtype: int64

In [59]:
X = heart_data.drop("AHD", axis=1)
X.shape

(303, 14)

In [61]:
X_train, X_test, y_train, y_test = train_test_split(X, heart_data.loc[:, "AHD"].values, test_size = 0.33, random_state = 42) #số 42 random

min=np.min(X_train,axis=0)
max=np.max(X_train,axis=0)
X_train=(X_train-min)/(max-min)

X_test=(X_test-min)/(max-min)

X_train.shape


(203, 14)

In [63]:
X_train

Unnamed: 0       Age  Sex  ChestPain    RestBP      Chol  Fbs  RestECG  \
37     0.122517  0.534884  1.0   0.000000  0.528302  0.473881  0.0      1.0   
16     0.052980  0.325581  1.0   0.666667  0.150943  0.298507  0.0      0.0   
126    0.417219  0.511628  0.0   0.000000  1.000000  0.518657  1.0      1.0   
291    0.963576  0.488372  0.0   0.666667  0.358491  0.720149  0.0      0.0   
273    0.903974  0.860465  0.0   0.000000  0.169811  0.000000  0.0      0.0   
..          ...       ...  ...        ...       ...       ...  ...      ...   
188    0.622517  0.465116  1.0   0.666667  0.924528  0.500000  0.0      1.0   
71     0.235099  0.767442  1.0   0.000000  0.292453  0.391791  1.0      0.0   
106    0.350993  0.581395  1.0   0.000000  0.433962  0.104478  0.0      0.0   
270    0.894040  0.627907  1.0   0.000000  0.433962  0.216418  0.0      1.0   
102    0.337748  0.534884  0.0   0.000000  0.320755  0.574627  0.0      1.0   

        MaxHR  ExAng   Oldpeak  Slope        Ca      Thal  
37   0.330645    1.0  0.096774    0.5  0.333333  0.000000  
16   0.782258    0.0  0.161290    1.0  0.000000  0.666667  
126  0.500000    1.0  0.645161    1.0  0.666667  0.666667  
291  0.766129    0.0  0.193548    0.0  0.000000  0.333333  
273  0.435484    0.0  0.258065    0.5  0.000000  0.333333  
..        ...    ...       ...    ...       ...       ...  
188  1.000000    0.0  0.000000    0.0  0.333333  0.666667  
71   0.741935    0.0  0.032258    0.5  0.666667  0.666667  
106  0.733871    1.0  0.000000    0.0  0.333333  0.666667  
270  0.540323    1.0  0.306452    0.0  0.333333  0.666667  
102  0.709677    0.0  0.000000    0.0  0.333333  0.333333  

[203 rows x 14 columns]

In [62]:
from sklearn.linear_model import LogisticRegression
clf = LogisticRegression(random_state=0).fit(X_train, y_train)
clf.score(X_test,y_test)

0.85

In [67]:
from sklearn.metrics import accuracy_score
y_pred=clf.predict(X_test)
accuracy_score(y_test, y_pred)

0.85

In [71]:
from sklearn.metrics import recall_score
recall_score(y_test, y_pred)

0.8163265306122449

In [70]:
from sklearn.metrics import precision_score
precision_score(y_test,y_pred)

0.8695652173913043

In [72]:
from sklearn.metrics import roc_curve
roc_curve(y_test,y_pred)

(array([0.        , 0.11764706, 1.        ]),
 array([0.        , 0.81632653, 1.        ]),
 array([2, 1, 0]))